"""empty message

Revision ID: 8015ec3a9bde
Revises: 36dc26301798
Create Date: 2023-06-22 14:06:57.217167

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8015ec3a9bde'
down_revision = '36dc26301798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_code')
    # ### end Alembic commands ###
